Visual Studio Code (1.95.3, attached-container, desktop)
Jupyter Extension Version: 2024.10.0.
Python Extension Version: 2024.20.0.
Pylance Extension Version: 2024.11.2.
Platform: linux (x64).
Temp Storage folder ~/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2024.10.0
Workspace folder /container/pyspark_workspace, Home = /root
15:52:44.649 [info] Starting Kernel (Python Path: /usr/local/bin/python, Unknown, 3.11.9) for '/container/pyspark_workspace/source_code/sample_code/Test_Project_1.ipynb' (disableUI=true)
15:52:47.042 [warn] Failed to get activated env vars for /usr/local/bin/python in 2403ms
15:52:47.152 [info] Process Execution: /usr/local/bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
15:52:47.277 [warn] Failed to get activated env vars for /usr/local/bin/python in 2124ms
15:52:47.301 [info] Process Execution: /usr/local/bin/python -m pip list
15:52:47.324 [info] Process Execution: /usr/local/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
15:52:47.501 [info] Process Execution: /usr/local/bin/python -m ipykernel_launcher --f=/~/.local/share/jupyter/runtime/kernel-v3b00253ce2e0a8b22f966eff4338f8ce3b97279b9.json
    > cwd: //container/pyspark_workspace/source_code/sample_code
15:53:08.127 [info] Kernel successfully started
15:53:08.228 [info] Process Execution: /usr/local/bin/python /~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/pythonFiles/printJupyterDataDir.py
15:53:09.487 [warn] Cell completed with errors iu [Error]: libodbc.so.2: cannot open shared object file: No such file or directory
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ImportError',
  evalue: 'libodbc.so.2: cannot open shared object file: No such file or directory',
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mImportError\x1B[0m                               Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[1], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mpyodbc\x1B[39;00m\n',
    '\x1B[0;31mImportError\x1B[0m: libodbc.so.2: cannot open shared object file: No such file or directory'
  ]
}
15:57:19.917 [warn] Cell completed with errors iu [Error]: libodbc.so.2: cannot open shared object file: No such file or directory
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ImportError',
  evalue: 'libodbc.so.2: cannot open shared object file: No such file or directory',
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mImportError\x1B[0m                               Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[3], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mpyodbc\x1B[39;00m\n',
    '\x1B[0;31mImportError\x1B[0m: libodbc.so.2: cannot open shared object file: No such file or directory'
  ]
}
15:58:35.090 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd06699b966c21a81be21759e40053de52c009daad87cbe5a3dc643468ce4ab3367.d:\Program Files\Python\python.exe.d:\Program Files\Python\python.exe.-m#ipykernel_launcher' for view = 'jupyter-notebook'
15:58:35.092 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd06699b966c21a81be21759e40053de52c009daad87cbe5a3dc643468ce4ab3367.d:\Program Files\Python\python.exe.d:\Program Files\Python\python.exe.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
15:59:26.573 [info] Starting Kernel (Python Path: /usr/local/bin/python, Unknown, 3.11.9) for '/container/pyspark_workspace/source_code/sample_code/Test_Kafka.ipynb' (disableUI=true)
15:59:29.546 [warn] Failed to get activated env vars for /usr/local/bin/python in 2906ms
15:59:29.565 [info] Process Execution: /usr/local/bin/python -m pip list
15:59:29.745 [warn] Failed to get activated env vars for /usr/local/bin/python in 3014ms
15:59:29.769 [info] Process Execution: /usr/local/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
15:59:29.808 [info] Process Execution: /usr/local/bin/python -m ipykernel_launcher --f=/~/.local/share/jupyter/runtime/kernel-v36ea90e9c70f966eaf601dbf016225ec3f4fc67c7.json
    > cwd: //container/pyspark_workspace/source_code/sample_code
15:59:36.386 [info] Kernel successfully started
15:59:36.708 [info] Starting Kernel (Python Path: /usr/local/bin/python, Unknown, 3.11.9) for '/container/pyspark_workspace/source_code/common_function.ipynb' (disableUI=true)
15:59:37.758 [warn] Failed to get activated env vars for /usr/local/bin/python in 1014ms
15:59:37.773 [info] Process Execution: /usr/local/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
15:59:37.850 [info] Process Execution: /usr/local/bin/python -m ipykernel_launcher --f=/~/.local/share/jupyter/runtime/kernel-v3f4fa4b9b4dfe36c1b2daafacbb849b464f8bc7d3.json
    > cwd: //container/pyspark_workspace/source_code
15:59:43.574 [info] Kernel successfully started
16:03:22.817 [warn] Cell completed with errors iu [Error]: invalid syntax (939724698.py, line 1)
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'SyntaxError',
  evalue: 'invalid syntax (939724698.py, line 1)',
  traceback: [
    '\x1B[0;36m  Cell \x1B[0;32mIn[6], line 1\x1B[0;36m\x1B[0m\n' +
      '\x1B[0;31m    import ./common_function as common\x1B[0m\n' +
      '\x1B[0m           ^\x1B[0m\n' +
      '\x1B[0;31mSyntaxError\x1B[0m\x1B[0;31m:\x1B[0m invalid syntax\n'
  ]
}
16:03:50.505 [warn] Cell completed with errors iu [Error]: invalid syntax (1370786242.py, line 1)
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'SyntaxError',
  evalue: 'invalid syntax (1370786242.py, line 1)',
  traceback: [
    '\x1B[0;36m  Cell \x1B[0;32mIn[7], line 1\x1B[0;36m\x1B[0m\n' +
      '\x1B[0;31m    import source_code/common_function as common\x1B[0m\n' +
      '\x1B[0m                      ^\x1B[0m\n' +
      '\x1B[0;31mSyntaxError\x1B[0m\x1B[0;31m:\x1B[0m invalid syntax\n'
  ]
}
16:04:00.933 [warn] Cell completed with errors iu [Error]: invalid syntax (939724698.py, line 1)
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'SyntaxError',
  evalue: 'invalid syntax (939724698.py, line 1)',
  traceback: [
    '\x1B[0;36m  Cell \x1B[0;32mIn[8], line 1\x1B[0;36m\x1B[0m\n' +
      '\x1B[0;31m    import ./common_function as common\x1B[0m\n' +
      '\x1B[0m           ^\x1B[0m\n' +
      '\x1B[0;31mSyntaxError\x1B[0m\x1B[0;31m:\x1B[0m invalid syntax\n'
  ]
}
16:04:11.756 [warn] Cell completed with errors iu [Error]: invalid syntax (2228340238.py, line 1)
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'SyntaxError',
  evalue: 'invalid syntax (2228340238.py, line 1)',
  traceback: [
    '\x1B[0;36m  Cell \x1B[0;32mIn[9], line 1\x1B[0;36m\x1B[0m\n' +
      '\x1B[0;31m    from ./common_function import *\x1B[0m\n' +
      '\x1B[0m          ^\x1B[0m\n' +
      '\x1B[0;31mSyntaxError\x1B[0m\x1B[0;31m:\x1B[0m invalid syntax\n'
  ]
}
16:08:50.133 [warn] Cell completed with errors iu [Error]: No module named 'common_function'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'common_function'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[10], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01mcommon_function\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;241m*\x1B[39m\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'common_function'"
  ]
}
16:09:01.751 [warn] Cell completed with errors iu [Error]: invalid syntax (2520440511.py, line 1)
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'SyntaxError',
  evalue: 'invalid syntax (2520440511.py, line 1)',
  traceback: [
    '\x1B[0;36m  Cell \x1B[0;32mIn[11], line 1\x1B[0;36m\x1B[0m\n' +
      '\x1B[0;31m    from source_code/common_function import *\x1B[0m\n' +
      '\x1B[0m                    ^\x1B[0m\n' +
      '\x1B[0;31mSyntaxError\x1B[0m\x1B[0;31m:\x1B[0m invalid syntax\n'
  ]
}
16:09:08.837 [warn] Cell completed with errors iu [Error]: attempted relative import with no known parent package
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ImportError',
  evalue: 'attempted relative import with no known parent package',
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mImportError\x1B[0m                               Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[12], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01m.\x1B[39;00m\x1B[38;5;21;01m.\x1B[39;00m\x1B[38;5;21;01mcommon_function\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;241m*\x1B[39m\n',
    '\x1B[0;31mImportError\x1B[0m: attempted relative import with no known parent package'
  ]
}
16:09:20.580 [warn] Cell completed with errors iu [Error]: No module named 'source_code'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'source_code'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[13], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01msource_code\x1B[39;00m\x1B[38;5;21;01m.\x1B[39;00m\x1B[38;5;21;01mcommon_function\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;241m*\x1B[39m\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'source_code'"
  ]
}
16:10:50.215 [warn] Cell completed with errors iu [Error]: invalid syntax (1763070688.py, line 1)
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'SyntaxError',
  evalue: 'invalid syntax (1763070688.py, line 1)',
  traceback: [
    '\x1B[0;36m  Cell \x1B[0;32mIn[14], line 1\x1B[0;36m\x1B[0m\n' +
      '\x1B[0;31m    from ./source_code/common_function.ipynb import *\x1B[0m\n' +
      '\x1B[0m          ^\x1B[0m\n' +
      '\x1B[0;31mSyntaxError\x1B[0m\x1B[0;31m:\x1B[0m invalid syntax\n'
  ]
}
16:12:14.570 [warn] Cell completed with errors iu [Error]: File `'./utils.ipynb'` not found.
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'Exception',
  evalue: "File `'./utils.ipynb'` not found.",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mOSError\x1B[0m                                   Traceback (most recent call last)',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:720\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      '\x1B[1;32m    719\x1B[0m     fpath \x1B[38;5;241m=\x1B[39m arg_lst[\x1B[38;5;241m0\x1B[39m]\n' +
      '\x1B[0;32m--> 720\x1B[0m     filename \x1B[38;5;241m=\x1B[39m \x1B[43mfile_finder\x1B[49m\x1B[43m(\x1B[49m\x1B[43mfpath\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    721\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mIndexError\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m e:\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/utils/path.py:91\x1B[0m, in \x1B[0;36mget_py_filename\x1B[0;34m(name)\x1B[0m\n' +
      '\x1B[1;32m     90\x1B[0m         \x1B[38;5;28;01mreturn\x1B[39;00m py_name\n' +
      '\x1B[0;32m---> 91\x1B[0m \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mIOError\x1B[39;00m(\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mFile `\x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124m` not found.\x1B[39m\x1B[38;5;124m"\x1B[39m \x1B[38;5;241m%\x1B[39m name)\n',
    "\x1B[0;31mOSError\x1B[0m: File `'./utils.ipynb'` not found.",
    '\nThe above exception was the direct cause of the following exception:\n',
    '\x1B[0;31mException\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[15], line 1\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0m \x1B[43mget_ipython\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_line_magic\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43mrun\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m./utils.ipynb\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2480\x1B[0m, in \x1B[0;36mInteractiveShell.run_line_magic\x1B[0;34m(self, magic_name, line, _stack_depth)\x1B[0m\n' +
      "\x1B[1;32m   2478\x1B[0m     kwargs[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mlocal_ns\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mget_local_scope(stack_depth)\n" +
      '\x1B[1;32m   2479\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mbuiltin_trap:\n' +
      '\x1B[0;32m-> 2480\x1B[0m     result \x1B[38;5;241m=\x1B[39m \x1B[43mfn\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43margs\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43mkwargs\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   2482\x1B[0m \x1B[38;5;66;03m# The code below prevents the output from being displayed\x1B[39;00m\n' +
      '\x1B[1;32m   2483\x1B[0m \x1B[38;5;66;03m# when using magics with decorator @output_can_be_silenced\x1B[39;00m\n' +
      "\x1B[1;32m   2484\x1B[0m \x1B[38;5;66;03m# when the last Python token in the expression is a ';'.\x1B[39;00m\n" +
      '\x1B[1;32m   2485\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;28mgetattr\x1B[39m(fn, magic\x1B[38;5;241m.\x1B[39mMAGIC_OUTPUT_CAN_BE_SILENCED, \x1B[38;5;28;01mFalse\x1B[39;00m):\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:731\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      `\x1B[1;32m    729\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m os\x1B[38;5;241m.\x1B[39mname \x1B[38;5;241m==\x1B[39m \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mnt\x1B[39m\x1B[38;5;124m'\x1B[39m \x1B[38;5;129;01mand\x1B[39;00m re\x1B[38;5;241m.\x1B[39mmatch(\x1B[38;5;124mr\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m^\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m.*\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m$\x1B[39m\x1B[38;5;124m"\x1B[39m,fpath):\n` +
      `\x1B[1;32m    730\x1B[0m         warn(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mFor Windows, use double quotes to wrap a filename: \x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124mun \x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mmypath\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mmyfile.py\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m'\x1B[39m)\n` +
      '\x1B[0;32m--> 731\x1B[0m     \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mException\x1B[39;00m(msg) \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01me\x1B[39;00m\n' +
      '\x1B[1;32m    732\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mTypeError\x1B[39;00m:\n' +
      '\x1B[1;32m    733\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m fpath \x1B[38;5;129;01min\x1B[39;00m sys\x1B[38;5;241m.\x1B[39mmeta_path:\n',
    "\x1B[0;31mException\x1B[0m: File `'./utils.ipynb'` not found."
  ]
}
16:12:29.647 [warn] Cell completed with errors iu [Error]: File `'./utils.ipynb'` not found.
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'Exception',
  evalue: "File `'./utils.ipynb'` not found.",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mOSError\x1B[0m                                   Traceback (most recent call last)',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:720\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      '\x1B[1;32m    719\x1B[0m     fpath \x1B[38;5;241m=\x1B[39m arg_lst[\x1B[38;5;241m0\x1B[39m]\n' +
      '\x1B[0;32m--> 720\x1B[0m     filename \x1B[38;5;241m=\x1B[39m \x1B[43mfile_finder\x1B[49m\x1B[43m(\x1B[49m\x1B[43mfpath\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    721\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mIndexError\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m e:\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/utils/path.py:91\x1B[0m, in \x1B[0;36mget_py_filename\x1B[0;34m(name)\x1B[0m\n' +
      '\x1B[1;32m     90\x1B[0m         \x1B[38;5;28;01mreturn\x1B[39;00m py_name\n' +
      '\x1B[0;32m---> 91\x1B[0m \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mIOError\x1B[39;00m(\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mFile `\x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124m` not found.\x1B[39m\x1B[38;5;124m"\x1B[39m \x1B[38;5;241m%\x1B[39m name)\n',
    "\x1B[0;31mOSError\x1B[0m: File `'./utils.ipynb'` not found.",
    '\nThe above exception was the direct cause of the following exception:\n',
    '\x1B[0;31mException\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[16], line 1\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0m \x1B[43mget_ipython\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_line_magic\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43mrun\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m./utils.ipynb\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2480\x1B[0m, in \x1B[0;36mInteractiveShell.run_line_magic\x1B[0;34m(self, magic_name, line, _stack_depth)\x1B[0m\n' +
      "\x1B[1;32m   2478\x1B[0m     kwargs[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mlocal_ns\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mget_local_scope(stack_depth)\n" +
      '\x1B[1;32m   2479\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mbuiltin_trap:\n' +
      '\x1B[0;32m-> 2480\x1B[0m     result \x1B[38;5;241m=\x1B[39m \x1B[43mfn\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43margs\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43mkwargs\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   2482\x1B[0m \x1B[38;5;66;03m# The code below prevents the output from being displayed\x1B[39;00m\n' +
      '\x1B[1;32m   2483\x1B[0m \x1B[38;5;66;03m# when using magics with decorator @output_can_be_silenced\x1B[39;00m\n' +
      "\x1B[1;32m   2484\x1B[0m \x1B[38;5;66;03m# when the last Python token in the expression is a ';'.\x1B[39;00m\n" +
      '\x1B[1;32m   2485\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;28mgetattr\x1B[39m(fn, magic\x1B[38;5;241m.\x1B[39mMAGIC_OUTPUT_CAN_BE_SILENCED, \x1B[38;5;28;01mFalse\x1B[39;00m):\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:731\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      `\x1B[1;32m    729\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m os\x1B[38;5;241m.\x1B[39mname \x1B[38;5;241m==\x1B[39m \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mnt\x1B[39m\x1B[38;5;124m'\x1B[39m \x1B[38;5;129;01mand\x1B[39;00m re\x1B[38;5;241m.\x1B[39mmatch(\x1B[38;5;124mr\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m^\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m.*\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m$\x1B[39m\x1B[38;5;124m"\x1B[39m,fpath):\n` +
      `\x1B[1;32m    730\x1B[0m         warn(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mFor Windows, use double quotes to wrap a filename: \x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124mun \x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mmypath\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mmyfile.py\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m'\x1B[39m)\n` +
      '\x1B[0;32m--> 731\x1B[0m     \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mException\x1B[39;00m(msg) \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01me\x1B[39;00m\n' +
      '\x1B[1;32m    732\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mTypeError\x1B[39;00m:\n' +
      '\x1B[1;32m    733\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m fpath \x1B[38;5;129;01min\x1B[39;00m sys\x1B[38;5;241m.\x1B[39mmeta_path:\n',
    "\x1B[0;31mException\x1B[0m: File `'./utils.ipynb'` not found."
  ]
}
16:12:46.098 [warn] Cell completed with errors iu [Error]: No module named 'nbformat'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'nbformat'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[17], line 1\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0m \x1B[43mget_ipython\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_line_magic\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43mrun\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m../utils.ipynb\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2480\x1B[0m, in \x1B[0;36mInteractiveShell.run_line_magic\x1B[0;34m(self, magic_name, line, _stack_depth)\x1B[0m\n' +
      "\x1B[1;32m   2478\x1B[0m     kwargs[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mlocal_ns\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mget_local_scope(stack_depth)\n" +
      '\x1B[1;32m   2479\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mbuiltin_trap:\n' +
      '\x1B[0;32m-> 2480\x1B[0m     result \x1B[38;5;241m=\x1B[39m \x1B[43mfn\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43margs\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43mkwargs\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   2482\x1B[0m \x1B[38;5;66;03m# The code below prevents the output from being displayed\x1B[39;00m\n' +
      '\x1B[1;32m   2483\x1B[0m \x1B[38;5;66;03m# when using magics with decorator @output_can_be_silenced\x1B[39;00m\n' +
      "\x1B[1;32m   2484\x1B[0m \x1B[38;5;66;03m# when the last Python token in the expression is a ';'.\x1B[39;00m\n" +
      '\x1B[1;32m   2485\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;28mgetattr\x1B[39m(fn, magic\x1B[38;5;241m.\x1B[39mMAGIC_OUTPUT_CAN_BE_SILENCED, \x1B[38;5;28;01mFalse\x1B[39;00m):\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:741\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      "\x1B[1;32m    739\x1B[0m     \x1B[38;5;28;01mwith\x1B[39;00m preserve_keys(\x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mshell\x1B[38;5;241m.\x1B[39muser_ns, \x1B[38;5;124m'\x1B[39m\x1B[38;5;124m__file__\x1B[39m\x1B[38;5;124m'\x1B[39m):\n" +
      "\x1B[1;32m    740\x1B[0m         \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mshell\x1B[38;5;241m.\x1B[39muser_ns[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m__file__\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m filename\n" +
      '\x1B[0;32m--> 741\x1B[0m         \x1B[38;5;28;43mself\x1B[39;49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mshell\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43msafe_execfile_ipy\x1B[49m\x1B[43m(\x1B[49m\x1B[43mfilename\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mraise_exceptions\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[38;5;28;43;01mTrue\x1B[39;49;00m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    742\x1B[0m     \x1B[38;5;28;01mreturn\x1B[39;00m\n' +
      '\x1B[1;32m    744\x1B[0m \x1B[38;5;66;03m# Control the response to exit() calls made by the script being run\x1B[39;00m\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3002\x1B[0m, in \x1B[0;36mInteractiveShell.safe_execfile_ipy\x1B[0;34m(self, fname, shell_futures, raise_exceptions)\x1B[0m\n' +
      '\x1B[1;32m   3000\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m prepended_to_syspath(dname):\n' +
      '\x1B[1;32m   3001\x1B[0m     \x1B[38;5;28;01mtry\x1B[39;00m:\n' +
      '\x1B[0;32m-> 3002\x1B[0m \x1B[43m        \x1B[49m\x1B[38;5;28;43;01mfor\x1B[39;49;00m\x1B[43m \x1B[49m\x1B[43mcell\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;129;43;01min\x1B[39;49;00m\x1B[43m \x1B[49m\x1B[43mget_cells\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[43m:\x1B[49m\n' +
      '\x1B[1;32m   3003\x1B[0m \x1B[43m            \x1B[49m\x1B[43mresult\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43m \x1B[49m\x1B[38;5;28;43mself\x1B[39;49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_cell\x1B[49m\x1B[43m(\x1B[49m\x1B[43mcell\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43msilent\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[38;5;28;43;01mTrue\x1B[39;49;00m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mshell_futures\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43mshell_futures\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   3004\x1B[0m \x1B[43m            \x1B[49m\x1B[38;5;28;43;01mif\x1B[39;49;00m\x1B[43m \x1B[49m\x1B[43mraise_exceptions\x1B[49m\x1B[43m:\x1B[49m\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2990\x1B[0m, in \x1B[0;36mInteractiveShell.safe_execfile_ipy.<locals>.get_cells\x1B[0;34m()\x1B[0m\n' +
      '\x1B[1;32m   2988\x1B[0m \x1B[38;5;250m\x1B[39m\x1B[38;5;124;03m"""generator for sequence of code blocks to run"""\x1B[39;00m\n' +
      '\x1B[1;32m   2989\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m fname\x1B[38;5;241m.\x1B[39msuffix \x1B[38;5;241m==\x1B[39m \x1B[38;5;124m"\x1B[39m\x1B[38;5;124m.ipynb\x1B[39m\x1B[38;5;124m"\x1B[39m:\n' +
      '\x1B[0;32m-> 2990\x1B[0m     \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01mnbformat\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m read\n' +
      '\x1B[1;32m   2991\x1B[0m     nb \x1B[38;5;241m=\x1B[39m read(fname, as_version\x1B[38;5;241m=\x1B[39m\x1B[38;5;241m4\x1B[39m)\n' +
      '\x1B[1;32m   2992\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;129;01mnot\x1B[39;00m nb\x1B[38;5;241m.\x1B[39mcells:\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'nbformat'"
  ]
}
16:13:11.088 [warn] Cell completed with errors iu [Error]: File `'././utils.ipynb'` not found.
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'Exception',
  evalue: "File `'././utils.ipynb'` not found.",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mOSError\x1B[0m                                   Traceback (most recent call last)',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:720\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      '\x1B[1;32m    719\x1B[0m     fpath \x1B[38;5;241m=\x1B[39m arg_lst[\x1B[38;5;241m0\x1B[39m]\n' +
      '\x1B[0;32m--> 720\x1B[0m     filename \x1B[38;5;241m=\x1B[39m \x1B[43mfile_finder\x1B[49m\x1B[43m(\x1B[49m\x1B[43mfpath\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    721\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mIndexError\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m e:\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/utils/path.py:91\x1B[0m, in \x1B[0;36mget_py_filename\x1B[0;34m(name)\x1B[0m\n' +
      '\x1B[1;32m     90\x1B[0m         \x1B[38;5;28;01mreturn\x1B[39;00m py_name\n' +
      '\x1B[0;32m---> 91\x1B[0m \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mIOError\x1B[39;00m(\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mFile `\x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124m` not found.\x1B[39m\x1B[38;5;124m"\x1B[39m \x1B[38;5;241m%\x1B[39m name)\n',
    "\x1B[0;31mOSError\x1B[0m: File `'././utils.ipynb'` not found.",
    '\nThe above exception was the direct cause of the following exception:\n',
    '\x1B[0;31mException\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[18], line 1\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0m \x1B[43mget_ipython\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_line_magic\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43mrun\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m././utils.ipynb\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2480\x1B[0m, in \x1B[0;36mInteractiveShell.run_line_magic\x1B[0;34m(self, magic_name, line, _stack_depth)\x1B[0m\n' +
      "\x1B[1;32m   2478\x1B[0m     kwargs[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mlocal_ns\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mget_local_scope(stack_depth)\n" +
      '\x1B[1;32m   2479\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mbuiltin_trap:\n' +
      '\x1B[0;32m-> 2480\x1B[0m     result \x1B[38;5;241m=\x1B[39m \x1B[43mfn\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43margs\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43mkwargs\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   2482\x1B[0m \x1B[38;5;66;03m# The code below prevents the output from being displayed\x1B[39;00m\n' +
      '\x1B[1;32m   2483\x1B[0m \x1B[38;5;66;03m# when using magics with decorator @output_can_be_silenced\x1B[39;00m\n' +
      "\x1B[1;32m   2484\x1B[0m \x1B[38;5;66;03m# when the last Python token in the expression is a ';'.\x1B[39;00m\n" +
      '\x1B[1;32m   2485\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;28mgetattr\x1B[39m(fn, magic\x1B[38;5;241m.\x1B[39mMAGIC_OUTPUT_CAN_BE_SILENCED, \x1B[38;5;28;01mFalse\x1B[39;00m):\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:731\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      `\x1B[1;32m    729\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m os\x1B[38;5;241m.\x1B[39mname \x1B[38;5;241m==\x1B[39m \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mnt\x1B[39m\x1B[38;5;124m'\x1B[39m \x1B[38;5;129;01mand\x1B[39;00m re\x1B[38;5;241m.\x1B[39mmatch(\x1B[38;5;124mr\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m^\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m.*\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m$\x1B[39m\x1B[38;5;124m"\x1B[39m,fpath):\n` +
      `\x1B[1;32m    730\x1B[0m         warn(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mFor Windows, use double quotes to wrap a filename: \x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124mun \x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mmypath\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mmyfile.py\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m'\x1B[39m)\n` +
      '\x1B[0;32m--> 731\x1B[0m     \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mException\x1B[39;00m(msg) \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01me\x1B[39;00m\n' +
      '\x1B[1;32m    732\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mTypeError\x1B[39;00m:\n' +
      '\x1B[1;32m    733\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m fpath \x1B[38;5;129;01min\x1B[39;00m sys\x1B[38;5;241m.\x1B[39mmeta_path:\n',
    "\x1B[0;31mException\x1B[0m: File `'././utils.ipynb'` not found."
  ]
}
16:13:15.125 [warn] Cell completed with errors iu [Error]: No module named 'nbformat'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'nbformat'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[19], line 1\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0m \x1B[43mget_ipython\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_line_magic\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43mrun\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m.././utils.ipynb\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2480\x1B[0m, in \x1B[0;36mInteractiveShell.run_line_magic\x1B[0;34m(self, magic_name, line, _stack_depth)\x1B[0m\n' +
      "\x1B[1;32m   2478\x1B[0m     kwargs[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mlocal_ns\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mget_local_scope(stack_depth)\n" +
      '\x1B[1;32m   2479\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mbuiltin_trap:\n' +
      '\x1B[0;32m-> 2480\x1B[0m     result \x1B[38;5;241m=\x1B[39m \x1B[43mfn\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43margs\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43mkwargs\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   2482\x1B[0m \x1B[38;5;66;03m# The code below prevents the output from being displayed\x1B[39;00m\n' +
      '\x1B[1;32m   2483\x1B[0m \x1B[38;5;66;03m# when using magics with decorator @output_can_be_silenced\x1B[39;00m\n' +
      "\x1B[1;32m   2484\x1B[0m \x1B[38;5;66;03m# when the last Python token in the expression is a ';'.\x1B[39;00m\n" +
      '\x1B[1;32m   2485\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;28mgetattr\x1B[39m(fn, magic\x1B[38;5;241m.\x1B[39mMAGIC_OUTPUT_CAN_BE_SILENCED, \x1B[38;5;28;01mFalse\x1B[39;00m):\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:741\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      "\x1B[1;32m    739\x1B[0m     \x1B[38;5;28;01mwith\x1B[39;00m preserve_keys(\x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mshell\x1B[38;5;241m.\x1B[39muser_ns, \x1B[38;5;124m'\x1B[39m\x1B[38;5;124m__file__\x1B[39m\x1B[38;5;124m'\x1B[39m):\n" +
      "\x1B[1;32m    740\x1B[0m         \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mshell\x1B[38;5;241m.\x1B[39muser_ns[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m__file__\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m filename\n" +
      '\x1B[0;32m--> 741\x1B[0m         \x1B[38;5;28;43mself\x1B[39;49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mshell\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43msafe_execfile_ipy\x1B[49m\x1B[43m(\x1B[49m\x1B[43mfilename\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mraise_exceptions\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[38;5;28;43;01mTrue\x1B[39;49;00m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    742\x1B[0m     \x1B[38;5;28;01mreturn\x1B[39;00m\n' +
      '\x1B[1;32m    744\x1B[0m \x1B[38;5;66;03m# Control the response to exit() calls made by the script being run\x1B[39;00m\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3002\x1B[0m, in \x1B[0;36mInteractiveShell.safe_execfile_ipy\x1B[0;34m(self, fname, shell_futures, raise_exceptions)\x1B[0m\n' +
      '\x1B[1;32m   3000\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m prepended_to_syspath(dname):\n' +
      '\x1B[1;32m   3001\x1B[0m     \x1B[38;5;28;01mtry\x1B[39;00m:\n' +
      '\x1B[0;32m-> 3002\x1B[0m \x1B[43m        \x1B[49m\x1B[38;5;28;43;01mfor\x1B[39;49;00m\x1B[43m \x1B[49m\x1B[43mcell\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;129;43;01min\x1B[39;49;00m\x1B[43m \x1B[49m\x1B[43mget_cells\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[43m:\x1B[49m\n' +
      '\x1B[1;32m   3003\x1B[0m \x1B[43m            \x1B[49m\x1B[43mresult\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43m \x1B[49m\x1B[38;5;28;43mself\x1B[39;49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_cell\x1B[49m\x1B[43m(\x1B[49m\x1B[43mcell\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43msilent\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[38;5;28;43;01mTrue\x1B[39;49;00m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mshell_futures\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43mshell_futures\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   3004\x1B[0m \x1B[43m            \x1B[49m\x1B[38;5;28;43;01mif\x1B[39;49;00m\x1B[43m \x1B[49m\x1B[43mraise_exceptions\x1B[49m\x1B[43m:\x1B[49m\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2990\x1B[0m, in \x1B[0;36mInteractiveShell.safe_execfile_ipy.<locals>.get_cells\x1B[0;34m()\x1B[0m\n' +
      '\x1B[1;32m   2988\x1B[0m \x1B[38;5;250m\x1B[39m\x1B[38;5;124;03m"""generator for sequence of code blocks to run"""\x1B[39;00m\n' +
      '\x1B[1;32m   2989\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m fname\x1B[38;5;241m.\x1B[39msuffix \x1B[38;5;241m==\x1B[39m \x1B[38;5;124m"\x1B[39m\x1B[38;5;124m.ipynb\x1B[39m\x1B[38;5;124m"\x1B[39m:\n' +
      '\x1B[0;32m-> 2990\x1B[0m     \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01mnbformat\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m read\n' +
      '\x1B[1;32m   2991\x1B[0m     nb \x1B[38;5;241m=\x1B[39m read(fname, as_version\x1B[38;5;241m=\x1B[39m\x1B[38;5;241m4\x1B[39m)\n' +
      '\x1B[1;32m   2992\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;129;01mnot\x1B[39;00m nb\x1B[38;5;241m.\x1B[39mcells:\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'nbformat'"
  ]
}
16:13:25.750 [warn] Cell completed with errors iu [Error]: File `'/..utils.ipynb'` not found.
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'Exception',
  evalue: "File `'/..utils.ipynb'` not found.",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mOSError\x1B[0m                                   Traceback (most recent call last)',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:720\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      '\x1B[1;32m    719\x1B[0m     fpath \x1B[38;5;241m=\x1B[39m arg_lst[\x1B[38;5;241m0\x1B[39m]\n' +
      '\x1B[0;32m--> 720\x1B[0m     filename \x1B[38;5;241m=\x1B[39m \x1B[43mfile_finder\x1B[49m\x1B[43m(\x1B[49m\x1B[43mfpath\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    721\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mIndexError\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m e:\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/utils/path.py:91\x1B[0m, in \x1B[0;36mget_py_filename\x1B[0;34m(name)\x1B[0m\n' +
      '\x1B[1;32m     90\x1B[0m         \x1B[38;5;28;01mreturn\x1B[39;00m py_name\n' +
      '\x1B[0;32m---> 91\x1B[0m \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mIOError\x1B[39;00m(\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mFile `\x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124m` not found.\x1B[39m\x1B[38;5;124m"\x1B[39m \x1B[38;5;241m%\x1B[39m name)\n',
    "\x1B[0;31mOSError\x1B[0m: File `'/..utils.ipynb'` not found.",
    '\nThe above exception was the direct cause of the following exception:\n',
    '\x1B[0;31mException\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[20], line 1\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0m \x1B[43mget_ipython\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_line_magic\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43mrun\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m/..utils.ipynb\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2480\x1B[0m, in \x1B[0;36mInteractiveShell.run_line_magic\x1B[0;34m(self, magic_name, line, _stack_depth)\x1B[0m\n' +
      "\x1B[1;32m   2478\x1B[0m     kwargs[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mlocal_ns\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mget_local_scope(stack_depth)\n" +
      '\x1B[1;32m   2479\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mbuiltin_trap:\n' +
      '\x1B[0;32m-> 2480\x1B[0m     result \x1B[38;5;241m=\x1B[39m \x1B[43mfn\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43margs\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43mkwargs\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   2482\x1B[0m \x1B[38;5;66;03m# The code below prevents the output from being displayed\x1B[39;00m\n' +
      '\x1B[1;32m   2483\x1B[0m \x1B[38;5;66;03m# when using magics with decorator @output_can_be_silenced\x1B[39;00m\n' +
      "\x1B[1;32m   2484\x1B[0m \x1B[38;5;66;03m# when the last Python token in the expression is a ';'.\x1B[39;00m\n" +
      '\x1B[1;32m   2485\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;28mgetattr\x1B[39m(fn, magic\x1B[38;5;241m.\x1B[39mMAGIC_OUTPUT_CAN_BE_SILENCED, \x1B[38;5;28;01mFalse\x1B[39;00m):\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:731\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      `\x1B[1;32m    729\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m os\x1B[38;5;241m.\x1B[39mname \x1B[38;5;241m==\x1B[39m \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mnt\x1B[39m\x1B[38;5;124m'\x1B[39m \x1B[38;5;129;01mand\x1B[39;00m re\x1B[38;5;241m.\x1B[39mmatch(\x1B[38;5;124mr\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m^\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m.*\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m$\x1B[39m\x1B[38;5;124m"\x1B[39m,fpath):\n` +
      `\x1B[1;32m    730\x1B[0m         warn(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mFor Windows, use double quotes to wrap a filename: \x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124mun \x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mmypath\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mmyfile.py\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m'\x1B[39m)\n` +
      '\x1B[0;32m--> 731\x1B[0m     \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mException\x1B[39;00m(msg) \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01me\x1B[39;00m\n' +
      '\x1B[1;32m    732\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mTypeError\x1B[39;00m:\n' +
      '\x1B[1;32m    733\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m fpath \x1B[38;5;129;01min\x1B[39;00m sys\x1B[38;5;241m.\x1B[39mmeta_path:\n',
    "\x1B[0;31mException\x1B[0m: File `'/..utils.ipynb'` not found."
  ]
}
16:13:31.222 [warn] Cell completed with errors iu [Error]: File `'/../utils.ipynb'` not found.
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'Exception',
  evalue: "File `'/../utils.ipynb'` not found.",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mOSError\x1B[0m                                   Traceback (most recent call last)',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:720\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      '\x1B[1;32m    719\x1B[0m     fpath \x1B[38;5;241m=\x1B[39m arg_lst[\x1B[38;5;241m0\x1B[39m]\n' +
      '\x1B[0;32m--> 720\x1B[0m     filename \x1B[38;5;241m=\x1B[39m \x1B[43mfile_finder\x1B[49m\x1B[43m(\x1B[49m\x1B[43mfpath\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    721\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mIndexError\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m e:\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/utils/path.py:91\x1B[0m, in \x1B[0;36mget_py_filename\x1B[0;34m(name)\x1B[0m\n' +
      '\x1B[1;32m     90\x1B[0m         \x1B[38;5;28;01mreturn\x1B[39;00m py_name\n' +
      '\x1B[0;32m---> 91\x1B[0m \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mIOError\x1B[39;00m(\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mFile `\x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124m` not found.\x1B[39m\x1B[38;5;124m"\x1B[39m \x1B[38;5;241m%\x1B[39m name)\n',
    "\x1B[0;31mOSError\x1B[0m: File `'/../utils.ipynb'` not found.",
    '\nThe above exception was the direct cause of the following exception:\n',
    '\x1B[0;31mException\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[21], line 1\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0m \x1B[43mget_ipython\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mrun_line_magic\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43mrun\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m/../utils.ipynb\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2480\x1B[0m, in \x1B[0;36mInteractiveShell.run_line_magic\x1B[0;34m(self, magic_name, line, _stack_depth)\x1B[0m\n' +
      "\x1B[1;32m   2478\x1B[0m     kwargs[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mlocal_ns\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m=\x1B[39m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mget_local_scope(stack_depth)\n" +
      '\x1B[1;32m   2479\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m \x1B[38;5;28mself\x1B[39m\x1B[38;5;241m.\x1B[39mbuiltin_trap:\n' +
      '\x1B[0;32m-> 2480\x1B[0m     result \x1B[38;5;241m=\x1B[39m \x1B[43mfn\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43margs\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[38;5;241;43m*\x1B[39;49m\x1B[43mkwargs\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   2482\x1B[0m \x1B[38;5;66;03m# The code below prevents the output from being displayed\x1B[39;00m\n' +
      '\x1B[1;32m   2483\x1B[0m \x1B[38;5;66;03m# when using magics with decorator @output_can_be_silenced\x1B[39;00m\n' +
      "\x1B[1;32m   2484\x1B[0m \x1B[38;5;66;03m# when the last Python token in the expression is a ';'.\x1B[39;00m\n" +
      '\x1B[1;32m   2485\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;28mgetattr\x1B[39m(fn, magic\x1B[38;5;241m.\x1B[39mMAGIC_OUTPUT_CAN_BE_SILENCED, \x1B[38;5;28;01mFalse\x1B[39;00m):\n',
    'File \x1B[0;32m/usr/local/lib/python3.11/site-packages/IPython/core/magics/execution.py:731\x1B[0m, in \x1B[0;36mExecutionMagics.run\x1B[0;34m(self, parameter_s, runner, file_finder)\x1B[0m\n' +
      `\x1B[1;32m    729\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m os\x1B[38;5;241m.\x1B[39mname \x1B[38;5;241m==\x1B[39m \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mnt\x1B[39m\x1B[38;5;124m'\x1B[39m \x1B[38;5;129;01mand\x1B[39;00m re\x1B[38;5;241m.\x1B[39mmatch(\x1B[38;5;124mr\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m^\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m.*\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m$\x1B[39m\x1B[38;5;124m"\x1B[39m,fpath):\n` +
      `\x1B[1;32m    730\x1B[0m         warn(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mFor Windows, use double quotes to wrap a filename: \x1B[39m\x1B[38;5;132;01m%r\x1B[39;00m\x1B[38;5;124mun \x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mmypath\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mmyfile.py\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m'\x1B[39m)\n` +
      '\x1B[0;32m--> 731\x1B[0m     \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mException\x1B[39;00m(msg) \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01me\x1B[39;00m\n' +
      '\x1B[1;32m    732\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mTypeError\x1B[39;00m:\n' +
      '\x1B[1;32m    733\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m fpath \x1B[38;5;129;01min\x1B[39;00m sys\x1B[38;5;241m.\x1B[39mmeta_path:\n',
    "\x1B[0;31mException\x1B[0m: File `'/../utils.ipynb'` not found."
  ]
}
16:16:50.461 [info] Too many pending requests 1 for kernel 52eaef88-52d4-47ba-9fc9-5358c7410c53, waiting for it to be ready.
16:17:47.737 [info] Disposing request as the cell (-1) was deleted /container/pyspark_workspace/source_code/sample_code/Test_Project_1.ipynb
16:17:47.737 [info] Disposing request as the cell (-1) was deleted /container/pyspark_workspace/source_code/sample_code/Test_Project_1.ipynb
16:17:47.737 [info] Disposing request as the cell (-1) was deleted /container/pyspark_workspace/source_code/sample_code/Test_Project_1.ipynb
16:18:35.603 [warn] Cell completed with errors iu [Error]: No module named 'utils'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'utils'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[27], line 3\x1B[0m\n' +
      '\x1B[1;32m      1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01msys\x1B[39;00m\n' +
      "\x1B[1;32m      2\x1B[0m sys\x1B[38;5;241m.\x1B[39mpath\x1B[38;5;241m.\x1B[39minsert(\x1B[38;5;241m0\x1B[39m, \x1B[38;5;124mr\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m/container/pyspark_workspace/source_code/sample_code\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[0;32m----> 3\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mutils\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m \x1B[38;5;21;01mutils\x1B[39;00m\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'utils'"
  ]
}
16:20:29.557 [warn] Cell completed with errors iu [Error]: No module named 'utils'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'utils'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[28], line 3\x1B[0m\n' +
      '\x1B[1;32m      1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01msys\x1B[39;00m\n' +
      "\x1B[1;32m      2\x1B[0m sys\x1B[38;5;241m.\x1B[39mpath\x1B[38;5;241m.\x1B[39minsert(\x1B[38;5;241m0\x1B[39m, \x1B[38;5;124mr\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m/container/pyspark_workspace/source_code/sample_code\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[0;32m----> 3\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mutils\x1B[39;00m\x1B[38;5;21;01m.\x1B[39;00m\x1B[38;5;21;01mspark\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m \x1B[38;5;21;01mutils_spark\x1B[39;00m\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'utils'"
  ]
}
16:21:18.038 [warn] Cell completed with errors iu [Error]: No module named 'utils'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'utils'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[29], line 3\x1B[0m\n' +
      '\x1B[1;32m      1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01msys\x1B[39;00m\n' +
      "\x1B[1;32m      2\x1B[0m sys\x1B[38;5;241m.\x1B[39mpath\x1B[38;5;241m.\x1B[39minsert(\x1B[38;5;241m0\x1B[39m, \x1B[38;5;124mr\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m/container/pyspark_workspace/source_code/sample_code\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[0;32m----> 3\x1B[0m \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01mutils\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m spark \x1B[38;5;28;01mas\x1B[39;00m utils_spark\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'utils'"
  ]
}
16:21:30.265 [warn] Cell completed with errors iu [Error]: No module named 'utils'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'utils'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[30], line 3\x1B[0m\n' +
      '\x1B[1;32m      1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01msys\x1B[39;00m\n' +
      "\x1B[1;32m      2\x1B[0m sys\x1B[38;5;241m.\x1B[39mpath\x1B[38;5;241m.\x1B[39minsert(\x1B[38;5;241m0\x1B[39m, \x1B[38;5;124mr\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m/container/pyspark_workspace/source_code/sample_code\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[0;32m----> 3\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mutils\x1B[39;00m\x1B[38;5;21;01m.\x1B[39;00m\x1B[38;5;21;01mspark\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m \x1B[38;5;21;01mutils_spark\x1B[39;00m\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'utils'"
  ]
}
16:21:49.570 [warn] Cell completed with errors iu [Error]: No module named 'utils'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'utils'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[32], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mutils\x1B[39;00m\x1B[38;5;21;01m.\x1B[39;00m\x1B[38;5;21;01mspark\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m \x1B[38;5;21;01mutils_spark\x1B[39;00m\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'utils'"
  ]
}
16:23:36.217 [warn] Cell completed with errors iu [Error]: No module named 'utils'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'utils'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[33], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mutils\x1B[39;00m\x1B[38;5;21;01m.\x1B[39;00m\x1B[38;5;21;01mspark\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m \x1B[38;5;21;01mutils_spark\x1B[39;00m\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'utils'"
  ]
}
16:24:37.344 [warn] Cell completed with errors iu [Error]: No module named 'utils'
    at n.execute (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'utils'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[34], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01mutils\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m spark \x1B[38;5;28;01mas\x1B[39;00m utils_spark\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'utils'"
  ]
}
16:29:19.355 [info] Dispose Kernel '/container/pyspark_workspace/source_code/sample_code/Test_Kafka.ipynb' associated with '/container/pyspark_workspace/source_code/sample_code/Test_Kafka.ipynb'
16:29:24.819 [info] Starting Kernel (Python Path: /usr/local/bin/python, Unknown, 3.11.9) for '/container/pyspark_workspace/source_code/sample_code/Test_Kafka.ipynb' (disableUI=true)
16:29:25.112 [warn] Failed to get activated env vars for /usr/local/bin/python in 263ms
16:29:25.130 [info] Process Execution: /usr/local/bin/python -m pip list
16:29:25.230 [warn] Failed to get activated env vars for /usr/local/bin/python in 282ms
16:29:25.245 [info] Process Execution: /usr/local/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
16:29:25.282 [info] Process Execution: /usr/local/bin/python -m ipykernel_launcher --f=/~/.local/share/jupyter/runtime/kernel-v3b784994bd7e115897425f4b88d70cf327a3282f4.json
    > cwd: //container/pyspark_workspace/source_code/sample_code
16:29:30.684 [info] Kernel successfully started
16:43:48.710 [info] Dispose Kernel '/container/pyspark_workspace/source_code/sample_code/Test_Project_1.ipynb' associated with '/container/pyspark_workspace/source_code/sample_code/Test_Project_1.ipynb'
16:43:49.020 [info] Dispose Kernel '/container/pyspark_workspace/source_code/sample_code/Test_Kafka.ipynb' associated with '/container/pyspark_workspace/source_code/sample_code/Test_Kafka.ipynb'
16:43:49.020 [info] Dispose Kernel '/container/pyspark_workspace/source_code/common_function.ipynb' associated with '/container/pyspark_workspace/source_code/common_function.ipynb'
16:43:49.044 [info] Dispose Kernel '/container/pyspark_workspace/source_code/sample_code/Test_Kafka.ipynb' associated with '/container/pyspark_workspace/source_code/sample_code/Test_Kafka.ipynb'
16:43:51.102 [warn] Failed to delete connection file file:///~/.local/share/jupyter/runtime/kernel-v3b00253ce2e0a8b22f966eff4338f8ce3b97279b9.json for pid 1860 Canceled (FileSystemError): Canceled
    at Function.e (file:///~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:9853)
    at Object.stat (file:///~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:7007)
    at Bc.delete (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:239:15448)
    at /~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
16:43:51.135 [warn] Failed to delete connection file file:///~/.local/share/jupyter/runtime/kernel-v3f4fa4b9b4dfe36c1b2daafacbb849b464f8bc7d3.json for pid 4865 Canceled (FileSystemError): Canceled
    at Function.e (file:///~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:9853)
    at Object.stat (file:///~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:7007)
    at Bc.delete (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:239:15448)
    at /~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
16:43:51.138 [warn] Failed to delete connection file file:///~/.local/share/jupyter/runtime/kernel-v3b784994bd7e115897425f4b88d70cf327a3282f4.json for pid 18946 Canceled (FileSystemError): Canceled
    at Function.e (file:///~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:9853)
    at Object.stat (file:///~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:7007)
    at Bc.delete (/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:239:15448)
    at /~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
