[2024-11-21T12:37:38.029+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: step_1_import_data_dag.run_python_script manual__2024-11-21T12:32:31.223032+00:00 [queued]>
[2024-11-21T12:37:38.041+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: step_1_import_data_dag.run_python_script manual__2024-11-21T12:32:31.223032+00:00 [queued]>
[2024-11-21T12:37:38.042+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-11-21T12:37:38.107+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_python_script> on 2024-11-21 12:32:31.223032+00:00
[2024-11-21T12:37:38.112+0000] {standard_task_runner.py:57} INFO - Started process 2635 to run task
[2024-11-21T12:37:38.119+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'step_1_import_data_dag', 'run_python_script', 'manual__2024-11-21T12:32:31.223032+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/step_1_import_data_dag.py', '--cfg-path', '/tmp/tmp5yr6zka_']
[2024-11-21T12:37:38.124+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask run_python_script
[2024-11-21T12:37:38.297+0000] {task_command.py:415} INFO - Running <TaskInstance: step_1_import_data_dag.run_python_script manual__2024-11-21T12:32:31.223032+00:00 [running]> on host 6089584853a3
[2024-11-21T12:37:38.680+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='step_1_import_data_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T12:32:31.223032+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T12:32:31.223032+00:00'
[2024-11-21T12:37:38.682+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-21T12:37:38.683+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python_environment python ./source_code/generate_data/insert_dummy_data_into_CreditStagingDB.py']
[2024-11-21T12:37:38.695+0000] {subprocess.py:86} INFO - Output:
[2024-11-21T12:37:39.313+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-11-21T12:37:39.314+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-21T12:37:39.365+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-21T12:37:39.374+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=step_1_import_data_dag, task_id=run_python_script, execution_date=20241121T123231, start_date=20241121T123738, end_date=20241121T123739
[2024-11-21T12:37:39.463+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task run_python_script (Bash command failed. The command returned a non-zero exit code 1.; 2635)
[2024-11-21T12:37:39.499+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-21T12:37:39.560+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
