[2024-11-21T12:32:34.476+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: step_1_import_data_dag.run_python_script manual__2024-11-21T12:32:31.223032+00:00 [queued]>
[2024-11-21T12:32:34.489+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: step_1_import_data_dag.run_python_script manual__2024-11-21T12:32:31.223032+00:00 [queued]>
[2024-11-21T12:32:34.490+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-21T12:32:34.535+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_python_script> on 2024-11-21 12:32:31.223032+00:00
[2024-11-21T12:32:34.542+0000] {standard_task_runner.py:57} INFO - Started process 2527 to run task
[2024-11-21T12:32:34.551+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'step_1_import_data_dag', 'run_python_script', 'manual__2024-11-21T12:32:31.223032+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/step_1_import_data_dag.py', '--cfg-path', '/tmp/tmp7r0g7gmb']
[2024-11-21T12:32:34.558+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask run_python_script
[2024-11-21T12:32:34.818+0000] {task_command.py:415} INFO - Running <TaskInstance: step_1_import_data_dag.run_python_script manual__2024-11-21T12:32:31.223032+00:00 [running]> on host 6089584853a3
[2024-11-21T12:32:35.254+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='step_1_import_data_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T12:32:31.223032+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T12:32:31.223032+00:00'
[2024-11-21T12:32:35.275+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-21T12:32:35.276+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python ./source_code/generate_data/insert_dummy_data_into_CreditStagingDB.py']
[2024-11-21T12:32:35.293+0000] {subprocess.py:86} INFO - Output:
[2024-11-21T12:32:35.666+0000] {subprocess.py:93} INFO - python: can't open file './source_code/generate_data/insert_dummy_data_into_CreditStagingDB.py': [Errno 2] No such file or directory
[2024-11-21T12:32:35.673+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-21T12:32:35.740+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-21T12:32:35.747+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=step_1_import_data_dag, task_id=run_python_script, execution_date=20241121T123231, start_date=20241121T123234, end_date=20241121T123235
[2024-11-21T12:32:35.857+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task run_python_script (Bash command failed. The command returned a non-zero exit code 2.; 2527)
[2024-11-21T12:32:35.887+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-21T12:32:35.973+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
